# Generated by Django 4.2.5 on 2024-05-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_answers_id_alter_assessmentarea_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_name',
            new_name='name',
        ),
    ]
