# Generated by Django 4.2.5 on 2024-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_class_name_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='syndey_participant',
            new_name='syndey_percentile',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_score',
            field=models.FloatField(),
        ),
    ]
